export let json_data = {
  plans: [
    {
      id: 1,
      img: "https://www.runtastic.com/blog/wp-content/uploads/2018/05/optimizing-running-training-relaxation-stress-solar-boost-shoes.jpg",
      name: "Bulk",
      workouts: [
        {
          id: 1,
          name: "Push day 1",
          exercises: [
            {
              id: 1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id: 4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
      ],
    },
    {
      id: 2,
      img: "https://media1.popsugar-assets.com/files/thumbor/vfKZC1EoCN8Kmolk2Vrj8vpRpx4/fit-in/728xorig/filters:format_auto-!!-:strip_icc-!!-/2018/10/04/692/n/1922729/cb7f5be45bb63396984fc6.71791194_/i/Weekly-Workout-Plan-Women.jpg",
      name: "Lean",
      workouts: [
        {
          id: 1,
          name: "Push day 1",
          exercises: [
            {
              id: 1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id: 4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
      ],
    },
    {
      id: 4,
      img: "https://images.unsplash.com/photo-1530549387789-4c1017266635?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c3dpbW1pbmd8ZW58MHx8MHx8&w=1000&q=80",
      name: "Another",
      workouts: [
        {
          id: 1,
          name: "Push day 1",
          exercises: [
            {
              id: 1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id: 4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
        {
          id: 2,
          name: "Pull day 1",
          exercises: [
            {
              id: 1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id:3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id: 4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id:5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
        {
          id: 3,
          name: "Legs day 1",
          exercises: [
            {
              id: 1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id:2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id:4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
      ],
    },
    {
      id: 3,
      img: "https://i.ytimg.com/vi/gey73xiS8F4/maxresdefault.jpg",
      name: "Rest",
      workouts: [
        {
          id: 1,
          name: "Push day 1",
          exercises: [
            {
              id:1,
              dropset: true,
              superset: false,
              excersice_1_name: "Barbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: "15",
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id:2,
              dropset: false,
              superset: false,
              excersice_1_name: "Dumbell press",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "18",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id: 3,
              dropset: false,
              superset: true,
              excersice_1_name: "Chest Flies",
              excersice_1_sets: 3,
              excersice_1_reps: "10-12",
              excersice_1_dropset: "8-10",
              excersice_1_weigth: "22.5",
              excersice_1_dropset_weigth: null,
              excersice_2_name: "Tricep extension",
              excersice_2_sets: 3,
              excersice_2_reps: "10-12",
              excersice_2_weigth: "18",
            },
            {
              id: 4,
              dropset: false,
              superset: false,
              excersice_1_name: "Lateral raises",
              excersice_1_sets: 4,
              excersice_1_reps: "10-12",
              excersice_1_dropset: null,
              excersice_1_weigth: "8",
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
            {
              id:5,
              dropset: false,
              superset: false,
              excersice_1_name: "Dips",
              excersice_1_sets: 3,
              excersice_1_reps: "failure",
              excersice_1_dropset: null,
              excersice_1_weigth: null,
              excersice_1_dropset_weigth: null,
              excersice_2_name: null,
              excersice_2_sets: null,
              excersice_2_reps: null,
              excersice_2_weigth: null,
            },
          ],
        },
      ],
    },
  ],
};